services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./service-account.json:/app/service-account.json:ro
    env_file:
      - ./.env
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend