version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./service-account.json:/app/service-account.json:ro
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
